; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "BG Remover"
#define MyAppVersion "3.0.1"
#define MyAppPublisher "Meeran Rashith"
#define MyAppExeName "BGRemover.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{D3E6B4F1-5C2A-4B8D-9E7F-3A1B2C4D5E6F}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
; Install to user's local AppData to avoid Admin requirement
DefaultDirName={localappdata}\{#MyAppName}
DisableProgramGroupPage=yes
; Enforce 64-bit architecture for GPU/Memory stability
ArchitecturesAllowed=x64
ArchitecturesInstallIn64BitMode=x64
; Allow non-admin installation and running (simple click open)
PrivilegesRequired=lowest
OutputDir=.
OutputBaseFilename=BG_Remover_Setup
SetupIconFile=assets\app_icon.ico
UninstallDisplayIcon={app}\{#MyAppExeName}
LicenseFile=LICENSE.txt
Compression=lzma2/ultra64
InternalCompressLevel=max
SolidCompression=yes
WizardStyle=modern
CloseApplications=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; IMPORTANT: Update the path below to point to your build output directory (dist/app or dist/BGRemover)
Source: "dist\win\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
